name: Verify checklist
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  verify_checklist_pr:
    name: Verify checklist
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verifying the checklist
        uses: matterway/tools-skills-github-actions@main
